name: Build Ubuntu

on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: ⬇️ Fetch
        uses: actions/checkout@v4

      - name: ♨️ Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: 🤖 Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: ♨ Compose App Build
        run: ./gradlew :composeApp:clean :composeApp:assembleRelease

      - name:  iOS App Build
        run: xcodebuild -project ./iosApp/iosApp.xcodeproj -scheme iosApp -configuration Release OBJROOT=./build/ios SYMROOT=./SwiftTaskTracker/build/ios -destination id=C2732EE2-0B3C-4841-9CC5-9AAEE2892B81 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO